confdir /etc/chrony/conf.d

server 10.0.0.1 iburst prefer minpoll 2 maxpoll 4 xleave
server 10.0.2.1 iburst prefer minpoll 2 maxpoll 4 xleave


server s3-a-v4.time.yap.paw.net.uk iburst minpoll 2 maxpoll 4 xleave
server s3-a-v6.time.yap.paw.net.uk iburst minpoll 2 maxpoll 4 xleave

pool 0.openembedded.pool.ntp.org iburst

sourcedir /etc/chrony/sources.d

makestep 1.0 3

driftfile /var/lib/chrony/drift

rtcsync

logdir /var/log/chrony
